move flycheck test to -nw since bash doesn't support it
(it "flycheck squiggly appears underneath misspelled putStrLnORAORAORA function"
(find-file (emacs-d-directory-for "testdata/simple-haskell-project/Main.hs"))
(replace-string "putStrLn" "putStrLnORAORAORA")
(save-buffer)
(sit-for 1)
(expect (get-char-property (point) 'face) :to-equal 'flycheck-error))

results in:

Codygman's hci Haskell Integration flycheck squiggly appears underneath misspelled putStrLnORAORAORA function

Traceback (most recent call last):
  (perform-replace "putStrLn" "putStrLnORAORAORA" nil nil nil nil nil nil ni...
  (replace-match-maybe-edit "putStrLnORAORAORA" t t nil (69 77 #<buffer Main...
  (replace-match "putStrLnORAORAORA" t t)
  (ask-user-about-lock "/home/cody/hci/testdata/simple-haskell-project/Main....
  (error "Cannot resolve lock conflict in batch mode")
  (signal error ("Cannot resolve lock conflict in batch mode"))
error: (error "Cannot resolve lock conflict in batch mode")